task9/Task9.Core/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using task9.Models;
using Task9.Core.Services;

namespace Task9.Core
{
    public class CoursesController : Controller
    {
        private readonly ICourseService _courseService;

        public CoursesController(ICourseService service)
        {
            _courseService = service;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var courses = await _courseService.GetAll();
            return View(courses);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var course = await _courseService.Get(id);
            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NameCourse,Description")] Course course)
        {
            await _courseService.Add(course);
            return RedirectToAction(nameof(Index));
        }

        // GET: Courses/Edit/5

        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseService.Get(id);
            await _courseService.Update(course);
            return View(course);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NameCourse,Description")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }
            await _courseService.Update(course);
            return RedirectToAction(nameof(Index));
        }

        // GET: Courses/Delete/5

        public async Task<IActionResult> Delete(int? id)
        {
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> Delete(int id)
        {

            var course = await _courseService.Get(id);
            if (course == null)
            {
                return NotFound();
            }
            await _courseService.Delete(course);
            return View();
        }
    }
}

task9/Task9.Core/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using task9.Models;
using Task9.Core.Services;

namespace Task9.Core.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGroupService _groupService;

        public GroupsController(IGroupService service)
        {
            _groupService = service;
        }

        // GET: Groups
        public async Task<IActionResult> Index(int id)
        {
            if (id == 0) id = (int)TempData["CourseId"];
            ViewBag.CourseId = id;
            TempData["CourseId"] = id;
            var groups = await _groupService.GetAll4Course(id);
            return View(groups);
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int id)
        {

            var group = await _groupService.Get(id);
            return View(group);
        }

        public async Task<IActionResult> Create(int courseId)
        {
            ViewData["CourseId"] = new SelectList(new List<int> { courseId });
            TempData["CourseId"] = courseId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Name,CourseId")] Group group)
        {
            int cId = Convert.ToInt32(TempData["CourseId"]);
            group.CourseId = cId;
            await _groupService.Add(group);
            return RedirectToAction(nameof(Index), new { id = cId });
        }

        // GET: Groups/Edit/5

        public async Task<IActionResult> Edit(int id)
        {
            var group = await _groupService.Get(id);
            await _groupService.Update(group);
            return View(group);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CourseId")] Group group)
        {
            await _groupService.Update(group);
            return RedirectToAction(nameof(Index));
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            int cId = Convert.ToInt32(TempData["CourseId"]);
            var group = await _groupService.Get(id);
            await _groupService.Delete(group);
            return RedirectToAction(nameof(Index), new { id = cId });
        }
    }
}

task9/Task9.Core/Views/Courses/Create.cshtml
@model task9.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameCourse" class="control-label"></label>
                <input asp-for="NameCourse" class="form-control" />
                <span asp-validation-for="NameCourse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

task9/Task9.Core/Views/Courses/Delete.cshtml
@model task9.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameCourse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameCourse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

task9/Task9.Core/Views/Courses/Details.cshtml
@model task9.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NameCourse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NameCourse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

task9/Task9.Core/Views/Courses/Edit.cshtml
@model task9.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NameCourse" class="control-label"></label>
                <input asp-for="NameCourse" class="form-control" />
                <span asp-validation-for="NameCourse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

task9/Task9.Core/Views/Courses/Index.cshtml
@model IEnumerable<task9.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NameCourse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NameCourse)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>|
                    <a asp-action="Index" asp-controller="Groups" asp-route-id="@item.Id">Groups</a>
                </td>
            </tr>
        }
    </tbody>
</table>